# Deploy to freehosting FTP account
name: 🚀 Publish to mythaxis.co.uk

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Whatcha doing?'     
        required: true
        default: 'Deploying mythaxis inni 🎉'

jobs:
  printInputs:
    runs-on: ubuntu-20.04
    steps:
    - run: |
        echo "Log level: ${{ github.event.inputs.logLevel }}"

  FTP-Deploy-Action:
    name: 🎉 FTP-Deploy-Action
    runs-on: ubuntu-20.04
    steps:
    - name: 🚚 Get latest gh-pages content
      uses: actions/checkout@v3
      with:
        ref: 'gh-pages'

    - name: 📂 Sync files over FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.4
      with:
        server: ${{ secrets.FTP_SERVER2 }}
        username: ${{ secrets.FTP_USERNAME2 }}
        password: ${{ secrets.FTP_PASSWORD }}
        
